export const HOME_CASUAL = 'home_casual'; // 首页轮播图
export const HOME_NAV = 'home_nav'; // 首页导航
export const DRESS_NAV = 'dress_nav'; //服饰导航
export const BOX_NAV = 'box_nav'; //鞋包导航
export const BABY_NAV = 'baby_nav'; //母婴导航
export const GENERAL_NAV = 'general_nav'; //百货导航
export const FOOD_NAV = 'food_nav'; //百货导航
export const PHONE_NAV = 'phone_nav'; //手机导航
export const MAN_NAV = 'man_nav'; //运动导航
export const ELE_NAV = 'ele_nav'; //电器导航
export const HOME_SHOP_LIST = 'home_shop_list'; // 首页商品数据
export const RECOMMEND_SHOP_LIST = 'recommend_shop_list'; // 推荐商品数据
export const SEARCH_GOODS = 'search_goods'; // 搜索列表数据
export const USER_INFO = 'user_info'; // 同步用户信息
export const RESET_USER_INFO = 'reset_user_info'; // 清空用户信息
export const CART_SHOP_LIST = 'cart_shop_list'; // 购物车数据
export const ADD_SHOP_COUNT = 'add_shop_count'; // 增加购物车单个数据
export const REDUCE_SHOP_COUNT = 'reduce_shop_count'; // 减少购物车单个数据
export const SELECTED_ALL_GOODS = 'selected_all_goods'; // 是否选中所有的商品
export const SELECTED_SINGER_GOODS = 'selected_singer_goods'; // 单个商品的选中和取消
export const DEL_SINGER_GOODS = 'del_singer_goods'; // 单个商品的删除
